### PR TITLE
Add support for Electron 10

### PR DESCRIPTION
**Pull request by romansp**
Add new prebuild targets as Electron 10 has been released:
https://github.com/electron/electron/releases/tag/v10.0.0

### CODE REVIEW

**Comment by Kupstas** [comment]
I still have an error at electron 10. Are you sure that prebuild version exists?

**Comment by shiftkey** [comment]
@Kupstas please ensure that you are on `v7.0.0` or later, to get the prebuild version

**Comment by Kupstas** [comment]
I tried `7.3.0`

**Comment by Kupstas** [comment]
BTW do you have prebuild version for electron 11?

**Comment by shiftkey** [comment]
> I tried `7.3.0`

Please open a fresh issue with repro details

> BTW do you have prebuild version for electron 11?

Not currently. I'm not following the Node/Electron ecosystems closely these days to track when these new releases happen...

**Pull request merged**
