### PR TITLE
add prebuild support for Node 13

### PR DESCRIPTION
**Pull request by shiftkey**

### CODE REVIEW

**Comment by shiftkey** [comment]
Needs a `node-abi` update: https://github.com/lgeiger/node-abi/pull/74

**Comment by CodyJamesCasey** [comment]
Hey there @shiftkey! it looks like lgeiger/node-abi#74 went through and was cherry-picked into their master branch. Can this PR go through now?

**Comment by shiftkey** [comment]
@CodyJamesCasey thanks for the reminder!

I had to bump the package but it otherwise looks correct - let's see if I can publish a new update now.

**Comment by CodyJamesCasey** [comment]
Thanks so much @shiftkey! It's greatly appreciated =)

**Pull request merged**
