### PR TITLE
Make Linux module to be compatible with Google Chrome browser

### PR DESCRIPTION
**Pull request by gh4ck3r**
Credentials will be shared with Google Chrome browser

### CODE REVIEW

**Comment by TomasHubelbauer** [comment]
Does this mean that when one would use Keytar to store a credential, if they were to go to `chrome://settings/passwords`, they would find the stored credential there? And reversely, could Keytar then be used to retrieve passwords stored in Google Chrome?

**Comment by gh4ck3r** [comment]
I don't think credential that is stored by keytar will be shown in Chrome; I don't test it though. Because, Chrome doesn't store only URI and credentials but other values. But, it is possible with this patch that fetching credential that is stored from Chrome. This is my usual usecase.

One thing have to be sure is given URI to fetch credential have to be ended with '/'. e.g. https://service.com/ Since Chrome stores URI like that. So without slash at th end query will fail.

**Comment by gh4ck3r** [comment]
I just checked it's only compatible with reading. If keytar write existing credential of a service that is stored by Chrome, it'll make new credential that have same attribute i.e. "signon_realm". It can be checked via seahorse on Ubuntu.

**Comment by shiftkey** [comment]
This PR looks like a breaking change away from how we use `libsecret` on Linux, and without more context about these questions I can't take in this change:

 - What is the value in doing this? Does this make Chrome/Chromium a dependency for these users?
 - What's the story for existing users when they would upgrade to this version? What happens to their credentials that were stored in the old way?

**Comment by gh4ck3r** [comment]
> * What is the value in doing this? Does this make Chrome/Chromium a dependency for these users?
I don't think it's a dependency but a reference. Because, strings, I changed, are used by Google Chrome in Linux; I'm not sure about Chromium. So, if there's no Google Chrome, it doesn't matter as the strings works just as keys to find password. In other words, no matter how I changed the strings, there's no change of functionalities as long as there's no data stored with old strings.
> * What's the story for existing users when they would upgrade to this version? What happens to their credentials that were stored in the old way?
With this change, a user on Linux will get a password that's stored in Google Chrome.
If someone have credentials stored by node-keytar before this version, (s)he will be affected by this change because keys for URL and username is changed. But, IMHO, it's not that a problem because, I guess, people used to have same credential that's used by node-keytar and Google Chrome of their own.
This is exactly how I'm using node-keytar. I just don't want to store same credentials in separate for node-keytar and Google Chrome. Because, I have to update passwords time to time.

**Comment by shiftkey** [comment]
@gh4ck3r thanks for the extra information!

> With this change, a user on Linux will get a password that's stored in Google Chrome.
If someone have credentials stored by node-keytar before this version, (s)he will be affected by this change because keys for URL and username is changed.

Without a way to support existing installations that were previously working I cannot take in this change. By changing how credentials are stored for Linux users you are asking app developers to:

 - be aware that this new version is now looking at a different location, so they can avoid receiving reports from users about their credentials "going missing"
 - migrate whatever things were stored by their apps to this new location and convention
 - ensure storing credentials in this new location do not overwrite something else stored in Chrome by the user

> But, IMHO, it's not that a problem because, I guess, people used to have same credential that's used by node-keytar and Google Chrome of their own.

I disagree with this assumption. There's plenty of situations I can think of where third party applications should not be using credentials provided by the user (e.g. OAuth applications) and maintaining access tokens separate from user credentials means revocation becomes easier to manage for the user (and the application developer).

**Comment by gh4ck3r** [comment]
OK.. I got the point.
I didn't have enough consideration about 3rd party applications.
I just wanted to share my environment.

**Comment by shiftkey** [comment]
@gh4ck3r thanks for the idea and walking me through it from your side!

**Pull request closed without merging**
