### PR TITLE
Added support for a kwallet backend (Issue #17)

### PR DESCRIPTION
**Pull request by jathpala**
The original keytar_posix file is renamed to keytar_gnome and provides the gnome-keyring backend where supported. keytar_kde implements the same logic for a kwallet backend. A new keytar_posix file now acts as a wrapper which detects which backend to use and forwards requests to the appropriate backend implementation.

Various environment variables are used to guess which backend is the most appropriate.

kwallet is only supported for KDE Frameworks 5.

The main bug in this code is that openWallet will write to stderr via kDebug() when keytar is run as a command line program without a window associated with it. I'm nor sure how to disable this logging (other than redirecting stderr).

If anyone knows how to fix this error logging I'd love to update this code.

I've done some testing (mainly via KDE) and it seems to work as expected. I'd appreciate any further testing people could do of this code, particularly from GNOME and other desktop environments.

### CODE REVIEW

**Comment by jathpala** [comment]
Also, the travis CI build doesn't work because kwallet and Qt5 are required for this. Does anyone know how to update .travis.yml to add these libraries?

**Comment by shiftkey** [comment]
@jathpala I'm not sure what packages you'd need but [this section](https://github.com/atom/node-keytar/blob/master/.travis.yml#L5-L10) is likely where you'll need to include them...

**Comment by jathpala** [comment]
I think the problem with Travis is Ubuntu 12.04 doesn't support KDE5 and there's no ppa I'm aware of to add support. I tried Kubuntu backports but that isn't enough.

My patch requires addition dependencies of Qt5, kwindowsystem and kwallet. By upgraging to travis ubuntu 14.04 and adding the kubuntu backports ppa I can add in the Qt5 and kwindowsystem libraries but I can't find any way to add in kwallet5 as I think this only become available to the 14.10 backports.

What minimum dependencies do we want to have for this module? Are we happy to make KDE frameworks 5 as a dependency.

Do we make it a conditional compilation where the KDE wallet backend is only available if the user explicitly requests it at build time (and therefore has to have libkf5wallet available on their system)?

**Comment by jathpala** [comment]
I've modified my initial commit a little.

I've now added some pre-processor logic to only compile in kwallet support if the environment variable 'USE_KWALLET' is set to 1. This can be done by issuing 'export USE_KWALLET=1' prior to running npm install. This required some modifications to the build process also.

This certainly increases the code complexity compared to the initial commit (ec30712). The advantage here is that Qt5 and kwallet are no longer dependencies for users on gnome only. This also allows the travis build to complete successfully. Perhaps there's a way to do this more elegantly than my rather ugly implementation. Or perhaps it's better to just scrap the conditional compilation entirely and force Qt5 and kwallet as dependencies.

This still has a flaw in that kDebug output from openWallet() is still printed to stderr when running on the console.

**Comment by thesbros** [comment]
I was looking into this recently. Perhaps a better solution would be to require DBus (and not kwallet or libgnome-keyring), and use the [Secret Service API?](https://specifications.freedesktop.org/secret-service)

This is a standardized API that both KWallet and GNOME Keyring support. This would allow one implementation to be used for both, and any other wallets that may happen to support the API.

**Pull request closed without merging**
