### PR TITLE
Adds a findCredentials method which yields an array of account/password objects of all matching saved credentials #56

### LINKED ISSUE #56: Method to retrieve a list of services from the password manager.
I think adding a method that would give you a list of the stored services/accounts would be useful.  My current project needs this functionality.

I'm not good at c++ code, however, i know there are a lot of smart people in the community and i believe this would benefit the community as a whole.  If someone would be so kind as to create the methods for the OS's and then provide that to the javascript interface, i would be extremely grateful.

### PR DESCRIPTION
**Pull request by siebertm**
This PR addresses the need to find all accounts/password should you want to save multiple accounts in your keychain. Fixes #56

- [X] tests pass
- [X] lint passes
- [X] documentation added

If I missed anything, please tell me and I'll try to fix it.

### CODE REVIEW

**Comment by iolsen** [comment]
@BinaryMuse would you be willing to review this?

**Comment by siebertm** [comment]
@BinaryMuse thanks for your input! I incorporated your comments in my changes now - I actually fell over the `null` vs `[]` thing yesterday, too!

This should be ready now.

**Comment by BinaryMuse** [comment]
Thanks very much! This is great!

**Comment by BinaryMuse** [comment]
Version `4.1.0` has been released, incorporating this change. Thanks again!

**Pull request merged**
