### PR TITLE
Sync function for get Password added

### PR DESCRIPTION
**Pull request by karangoel16**
I have added Sync Get Functions i.e. which allows user to get Password without using Promises, hence can be used in code. If it is what we are interested in, I would be happy to write rest of the code over weekend. 

I faced challenge in writing a synchronous function using initial key-tar and made the following changes in it.

### CODE REVIEW

**Comment by shiftkey** [comment]
> I have added Sync Get Functions i.e. which allows user to get Password without using Promises, hence can be used in code.

@karangoel16 could you elaborate more on why you can't use the async API? I'd love to understand more about this use case...

**Comment by karangoel16** [comment]
1. So I saved crypto password randomly generated in keytar, and this password would further be used in decrypting database and encrypting, since it is a initializing function or constructor for the class, I just want to use it one time rather than calling it every time with promise. Constructor can't have promises within them as they can't be async. Also my class is singleton, so I am in fact calling the function just one time. So, the same could become really complex whereas if I make it sync, it is just one line. 

2. Also it is better provide user more choice of functions, If he wants to use it in synchronous manner within function, he should be allowed to do that, right ? 

Please do let me know if it has any downside for the same.

**Comment by karangoel16** [comment]
@shiftkey thank you for your reply will give it a try. I will try to see if I can provide more for the same or not.

**Comment by roblav96** [comment]
@karangoel16 Might I recommend a build-able class structure? Something I see everywhere in the Android AOSP code:
```typescript
class DatabaseSecurity extends AnotherClass {
	salt: string
	constructor(input: string) {
		super()
		this.salt = this.build()
		// or
		return this.build()
	}
	async build() {
		let stuff = await this.doStuff()
		this.doMoreStuff(stuff)
		return this
	}
	doStuff() {
		console.log(`this.salt ->`, this.salt)
	}
}

(async function() {
	let instance = await new DatabaseSecurity('hai')
})()
```
That might spark something 🤓

cc @shiftkey

**Comment by karangoel16** [comment]
Sure, I will try to implement the code @roblav96 , 

But my question still remains should not we allow programmers to choose between sync and async functions if we can.

as I know performance could be a factor when you run this code on server, when we run code in sync on server, but this keytar is also used with electron i.e. mainly on computer, we can fork this repository and make keytar-electron if we do not want changes on because it could slow down the server code, if not done properly on server.

@shiftkey , @roblav96

**Comment by shiftkey** [comment]
> But my question still remains should not we allow programmers to choose between sync and async functions if we can.

I found this even older comment asking why the APIs weren't asynchronous https://github.com/atom/node-keytar/issues/58, and pointed to the synchronous APIs actually being slower at the time:

> > They tend to be slower (around ~40ms on my 2015 MacBook Pro) and seems like there could be some benefit to making them non-blocking for performance reasons (especially as it's probably best to run node-keytar methods in the main process).

Node itself is built on technologies like [libuv](http://docs.libuv.org/en/v1.x/), and synchronous APIs can actually be slower due to how the runtime works.

That comment was cited in the work ages ago to move from synchronous to asynchronous APIs in https://github.com/atom/node-keytar/pull/63 to provide consistency across the modules that the Electron and Atom teams maintain, and I've not seen much feedback in terms of missing the old synchronous APIs since then.

> As I know performance could be a factor when you run this code on server, when we run code in sync on server, but this keytar is also used with electron i.e. mainly on computer, we can fork this repository and make keytar-electron if we do not want changes on because it could slow down the server code, if not done properly on server.

You are also welcome to fork this and maintain your own module which contains synchronous APIs. Electron apps make up a big part of keytar usage currently, and I want to continue to ensure they have first-class support here.

> Also, can somebody explain what would be other cons of having sync function in the code base please.

Some things that come to mind:

 - Maintenance (implementing and maintaining two sets code paths)
 - More support needed (because the API surface is now doubled)
 - Behaviour differences between sync and async internals (returning results, propagating errors, etc)
 - Performance unknowns (the asynchronous APIs are built upon libuv primitives, and it's not clear to me what the plan is for the sync APIs)

**Pull request closed without merging**
