### PR TITLE
Add prebuilds for Electron 12

### PR DESCRIPTION
**Pull request by azeier**
Electron 12 was released on Monday:
https://github.com/electron/electron/releases/tag/v12.0.0

### CODE REVIEW

**Comment by azeier** [comment]
The travis CI failure appears to be unrelated?
`
docker: Error response from daemon: pull access denied for node-keytar/arm64-cross-compile, repository does not exist or may require 'docker login'.
`

**Comment by David-Development** [comment]
Is there an ETA for this? Is there any way to build this locally until it is merged?

**Comment by azeier** [comment]
Updated for conflict with https://github.com/atom/node-keytar/commit/1d53fd5b3f147fe51ead85ba08c64842e346cf89.

@shiftkey Hey, any thing else I can do to help get this merged?

**Comment by sirtimid** [comment]
+1

**Comment by shiftkey** [comment]
> @shiftkey Hey, anything else I can do to help get this merged?

@azeier I'd ignore that Travis error but sadly that's required for publishing a new release so I'm chasing up getting admin rights so I can complete #334 and finally get away from Travis and Appveyor. Hopefully in the next day or so we can be ready to publish this in a release.

**Comment by shiftkey** [comment]
@azeier actually, this might be [a legit failure](https://travis-ci.org/github/atom/node-keytar/jobs/762024281#L723):

```
Error: Could not detect abi for version 12.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

Is this branch rebased on `master`? We updated `node-abi` recently which is often necessary when new Electron releases are available...

**Comment by azeier** [comment]
I initially had the node-abi upgrade in this PR as well, before master was updated. with the new node-abi version.

Though it looks like I just dropped that commit and didn't rebase. Did that now, let's see!

**Comment by azeier** [comment]
So it looks like the [original travis issue](https://travis-ci.org/github/atom/node-keytar/jobs/761373957) is now resolved on the [more recent linux builds](https://travis-ci.org/github/atom/node-keytar/jobs/762535225).

But the [osx build error](https://travis-ci.org/github/atom/node-keytar/jobs/762535226#L723) is still the same even with after the rebase on master.

**Comment by shiftkey** [comment]
I tested #366 fresh on top of the latest changes and I couldn't spot anything wrong.

Thanks for the contribution anyway @azeier!

**Pull request closed without merging**
