### PR TITLE
"Enterprise" persistence for Windows Credentials

### LINKED ISSUE #122: Windows Credential Vault: CRED_PERSIST_ENTERPRISE possible?
Hello & many thanks for providing `keytar`! I am currently working on a project that needs to run in a Windows Enterprise environment where passwords should be roamed for a user. Currently, local password storage is hardwired:

https://github.com/atom/node-keytar/blob/e48b67dd7f0ab409e982559a01d07e30bb5bb30a/src/keytar_win.cc#L136

Would it be possible to change this to `CRED_PERSIST_ENTERPRISE` as described [here](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/ns-wincred-_credentiala)? If I understand things correctly, this should lead to passwords being shared for a single user across an enterprise network.

### PR DESCRIPTION
**Pull request by jakobvogel**
This PR revises password storage on Microsoft Windows to claim "Enterprise" persistence instead of "Local Machine" persistence. This allows passwords to be roamed across enterprise networks, i.e. a certain single user will find his/her stored passwords when logging into different machines of the same network, should the administrator enable this.

This change should be reverse-compatible, as the credential manager will continue to find "old" entries with "Local Machine" persistence as well.

This PR closes #122.

**Before PR**
screen shot 2018-08-13 at 15 40 37

**After PR**
screen shot 2018-08-13 at 16 02 30

### CODE REVIEW

**Comment by jakobvogel** [comment]
Interestingly enough, _exactly_ the same issue was fixed a couple of days ago in a very similar library: https://github.com/frankosterfeld/qtkeychain/pull/121

**Comment by shiftkey** [comment]
cc @daviwil for :eyes

**Comment by jakobvogel** [comment]
Any news here? :)

**Comment by bkostjens** [comment]
Hello, in the latest version of keytar (4.4.1) the this is still not implemented?

keytar_win.cc has still cred.Persist = CRED_PERSIST_LOCAL_MACHINE;

For us this is also a problem as we want to deploy keytar in an enterprise environment. Any news?

**Comment by bkostjens** [comment]
I created a new issue for this:

https://github.com/atom/node-keytar/issues/168

**Comment by jakobvogel** [comment]
No, it is not implemented. We decided to fork the project and fix it ourselves there. Turned out to be simpler than waiting for a code review here, despite the extra work.

**Comment by bkostjens** [comment]
Thanks for responding. The big problem for me is that Im on macOS, but need to compile for windows as well. Without the precompiled packages, im not sure how to handle this?

**Comment by jakobvogel** [comment]
We’re also developing on macOS, but for the purpose of building the Windows variant, we run a separate Windows machine. We need the latter for code signing anyways. Our builds are just local at this time, though. 😔 I would definitely prefer to have that single line in the official code base.

**Pull request closed without merging**
