### PR TITLE
Changes persistence level to 'enterprise' on Windows

### LINKED ISSUE #168: Change cred.Persist to CRED_PERSIST_ENTERPRISE
Hello,

This has been requested before, but the pull request was never merged.

See: https://github.com/atom/node-keytar/pull/123

https://github.com/atom/node-keytar/blob/99d30585f5ae86153f71317ce24978fa9cede199/src/keytar_win.cc#L136

Would it be possible to change this (or make it configurable) to `CRED_PERSIST_ENTERPRISE`, so passwords don't get lost when logging out on a windows computer that is joined in a domain.

### PR DESCRIPTION
**Pull request by jakobvogel**
Restores #123. Closes #168.

### CODE REVIEW

**Comment by bkostjens** [comment]
Any update on the PR?

**Comment by shiftkey** [comment]
@bkostjens it's on my list to review this week - I want to do some verification of this behaviour to better understand the migration story (if needed) myself...

**Comment by bkostjens** [comment]
> @bkostjens it's on my list to review this week - I want to do some verification of this behaviour to better understand the migration story (if needed) myself...

Ah perfect! Thanks for your quick response.

**Comment by jakobvogel** [comment]
Thank you @shiftkey! 👍

**Comment by shiftkey** [comment]
@jakobvogel https://github.com/atom/node-keytar/releases/tag/v5.0.0-beta.0 is available to test out and verify you're happy with the change.

**Comment by jakobvogel** [comment]
> @jakobvogel https://github.com/atom/node-keytar/releases/tag/v5.0.0-beta.0 is available to test out and verify you're happy with the change.

I'll try it tomorrow and provide feedback here. Unfortunately, I currently don't have access to our Windows build machine. 😞

**Comment by jakobvogel** [comment]
I tried version 5.0.0 with our real product and everything works like a charm, both on macOS (where everything continues to work) and Windows (where credentials have enterprise persistence now). – Apart from the known issue #212, of course, but that does not matter to me too much right now.

So, I am very happy with version 5.0.0. 🎉 I am looking forward to retire our fork of the repository and move back to the official releases. Thanks again @shiftkey! 👍

**Pull request merged**
